CREATE TABLE IF NOT EXISTS flights (
    flight_id VARCHAR(20) NOT NULL,
    origin VARCHAR(80) NOT NULL,
    destination VARCHAR(80) NOT NULL,
    seat_class VARCHAR(30) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    total_seats INT NOT NULL,
    available_seats INT NOT NULL,
    approved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (flight_id, seat_class),
    CONSTRAINT chk_flights_price CHECK (price > 0),
    CONSTRAINT chk_flights_total_seats CHECK (total_seats > 0),
    CONSTRAINT chk_flights_available_seats CHECK (available_seats >= 0 AND available_seats <= total_seats)
);

CREATE TABLE IF NOT EXISTS pending_flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id VARCHAR(20) NOT NULL,
    origin VARCHAR(80) NOT NULL,
    destination VARCHAR(80) NOT NULL,
    seat_class VARCHAR(30) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    total_seats INT NOT NULL,
    available_seats INT NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_pending_flights_price CHECK (price > 0),
    CONSTRAINT chk_pending_flights_total_seats CHECK (total_seats > 0),
    CONSTRAINT chk_pending_flights_available_seats CHECK (available_seats >= 0 AND available_seats <= total_seats)
);

CREATE TABLE IF NOT EXISTS bookings (
    booking_id VARCHAR(50) PRIMARY KEY,
    username VARCHAR(120) NOT NULL,
    flight_id VARCHAR(20) NOT NULL,
    seat_class VARCHAR(30) NOT NULL,
    seat_count INT NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_bookings_flights FOREIGN KEY (flight_id, seat_class)
        REFERENCES flights (flight_id, seat_class),
    CONSTRAINT chk_bookings_seat_count CHECK (seat_count > 0),
    CONSTRAINT chk_bookings_total_price CHECK (total_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_flights_route ON flights (origin, destination);
CREATE INDEX IF NOT EXISTS idx_pending_flights_key ON pending_flights (flight_id, seat_class);
